site_name: PPG-quality
repo_url: https://github.com/peterhcharlton/ppg-quality
edit_uri: ''
site_description: PPG-quality, a Matlab library of algorithms to assess the quality of photoplethysmogram (PPG) signals
site_author: Peter H Charlton
copyright: Made available under the <a href = "https://creativecommons.org/licenses/by/4.0/">CC BY 4.0 license</a>

nav:
    - 'Home': 'index.md'
    - 'Toolbox':
      - 'Getting Started': './toolbox/getting_started.md'
      - 'PPG Quality Algorithms': './toolbox/ppg_quality_algorithms.md'
      - 'Contributing': './toolbox/contributing.md'
      - 'Acknowledgments': './toolbox/acknowledgments.md'
    - 'Functions':
      - 'assess_ppg_quality': './functions/assess_ppg_quality.md'
      - 'calc_amp_metrics': './functions/calc_amp_metrics.md'
      - 'calc_dtw': './functions/calc_dtw.md'
      - 'calc_morph_metrics': './functions/calc_morph_metrics.md'
      - 'calc_sig_sim': './functions/calc_sig_sim.md'
      - 'calc_snr': './functions/calc_snr.md'
      - 'calc_spectrum_metrics': './functions/calc_spectrum_metrics.md'
      - 'calc_stats_metrics': './functions/calc_stats_metrics.md'
      - 'calc_tm_cc': './functions/calc_tm_cc.md'
      - 'perform_beat_detection': './functions/perform_beat_detection.md'
      - 'perform_bpf': './functions/perform_bpf.md'
      - 'perform_med_ibi': './functions/perform_med_ibi.md'
      - 'perform_template_calc': './functions/perform_template_calc.md'
    - 'Tutorials':
      - 'Summary': './tutorials/summary.md'
      - 'PPG Quality Assessment': './tutorials/ppg_quality_assessment.md'
      - 'Creating Documentation': './tutorials/creating_docs.md'

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences